apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zpyb845x1-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/zpyb845x1-java-quarkus-gitops